### PR TITLE
DSWIFI v0.3.19

### PR DESCRIPTION
**Pull request by cotodevel**
Coto:
11/1/2016 (mm/dd/yyyy)
- spinlock.s SWP opcode gets compiled correctly for ARM7/ARM9
- Using 64K for heap.
- NesDS NIFI still broken.
- WIFI DHCP works (Youtube DS tested as host program).

[Notes]
Due to duplicates between wifi_shared.h and dswifi9.h I had move
duplicates from dswifi9.h to wifi_shared.h, and do dswifi9.h cleanup.

### CODE REVIEW

**Comment by AntonioND** [comment]
It is really difficult to understand the changes. You should have divided the commit into a few commits with simple changes, like the one doing the cleanup. Right now I can't even see what's exactly what you moved around because you are modifying 8 files in non-obvious ways. Also, the part of increasing the version number should be a different patch.

**Comment by cotodevel** [comment]
I made it as simple as possible, do a side by side comparison of the cleanup. Read again.

**Comment by AntonioND** [comment]
Commits should be unitary changes. You have squashed a few unitary changes into one commit, which makes it unnecessarily difficult for reviewers to understand the changes. I can think of at least 3 commits: reorganize code, apply changes, increase version number.

**Comment by AntonioND** [comment]
Also, dswifi 0.3.19 is a bad commit name because it doesn't explain the changes, and that happens because you can't explain so many things in one commit message.

**Comment by cotodevel** [comment]
Ok. Bye

**Pull request closed without merging**
