### PR TITLE
v0.3.18

### PR DESCRIPTION
**Pull request by cotodevel**
Updates:
Coto:(11/1/2016)
[Description]
Merged Wifi_RawTxFrame() (wifi_arm9.c) from v0.3.13, 
while maintaining both ARM7/ARM9 from 0.3.17.

[Notes]
Wifi_RawTxFrame():
Having done a side-by-side comparison, framelen size handles 
upcoming storage TX Buffer differently (better imho) then sends the frame 
accordingly by building LLC headers and so on.
Also, NIFI layer relies on a well formed packet, otherwise it does not work.

[Tests]
NIFI(NesDS) & WIFI DHCP TCP/IP (YoutubeDS) working all ok.

[Version] 
0.3.18

### CODE REVIEW

**Comment by WinterMute** [comment]
There are too many changes per commit in this pull request.

Some suggestions:

- Don't make your commits on the master branch of your fork, use a feature branch.
- Please don't make whitespace changes, it makes it very difficult to see what's actually changed.
- Please don't add credits or notes on the changes to the README. That's what commit messages are for.

Can you start with a new pull request for just the spinlock changes?

Why have you changed the default heap size from 64K to 128K?

**Comment by cotodevel** [comment]
1) v0.3.18 #1 would be the only branch you should focus on. I'll commit in parts, and you should only read what's based on that.

2) whilespace changes? I use notepad++ and Windows, I really didn't add those whitespaces. I always use TABs.

3) README notes will be moved to CHANGES, besides commit messages.

Tell me if you agree, or I should maintain v0.3.18 on my own.

Have a nice day

**Comment by WinterMute** [comment]
Whitespace changes include eol markers. In this PR it looks like you've changed the entirety of spinlock.s when the majority of your changes are whitespace.

Changing whitespace along with code makes it difficult to see what's actually changed in the code.

There should be a single commit for the spinlock changes which looks something like this

diff --git a/arm7/Makefile b/arm7/Makefile
index f145b4d..3299e2f 100644
--- a/arm7/Makefile
+++ b/arm7/Makefile
@@ -26,7 +26,7 @@ DATA		:=
 #---------------------------------------------------------------------------------
 ARCH	:=	-mthumb-interwork
 
-CFLAGS	:=	-g -Wall -Os\
+CFLAGS	:=	-Wall -Os\
 			-mcpu=arm7tdmi -mtune=arm7tdmi -fomit-frame-pointer\
 			-ffast-math \
 			$(ARCH)
@@ -35,7 +35,7 @@ CFLAGS	+=	$(INCLUDE) -DARM7
 CXXFLAGS	:=	$(CFLAGS)
 
 
-ASFLAGS	:=	-g $(ARCH)
+ASFLAGS	:=	$(INCLUDE) -DARM7 $(ARCH)
 LDFLAGS	=	-specs=ds_arm7.specs -g $(ARCH) -Wl,-Map,$(notdir $*).map
 
 
diff --git a/arm9/Makefile b/arm9/Makefile
index a07cbde..ffde3e4 100644
--- a/arm9/Makefile
+++ b/arm9/Makefile
@@ -26,7 +26,7 @@ DATA		:=	data
 #---------------------------------------------------------------------------------
 ARCH	:=	-mthumb -mthumb-interwork
 
-CFLAGS	:=	-g -Wall -Os\
+CFLAGS	:=	-Wall -Os\
  			-march=armv5te -mtune=arm946e-s -fomit-frame-pointer\
 			-ffast-math \
 			$(ARCH)
@@ -34,7 +34,7 @@ CFLAGS	:=	-g -Wall -Os\
 CFLAGS	+=	$(INCLUDE) -DARM9
 CXXFLAGS	:=	$(CFLAGS)
 
-ASFLAGS	:=	-g $(ARCH)
+ASFLAGS	:=	$(INCLUDE) -DARM9 $(ARCH)
 LDFLAGS	=	-specs=ds_arm9.specs -g $(ARCH) -Wl,-Map,$(notdir $*.map)
 
 ifneq ($(BUILD),debug)
diff --git a/common/source/spinlock.s b/common/source/spinlock.s
index efcb815..d1855c0 100644
--- a/common/source/spinlock.s
+++ b/common/source/spinlock.s
@@ -1,5 +1,10 @@
-	.arch	armv5te
-	.cpu	arm946e-s
+#ifdef ARM7
+	.cpu arm7tdmi
+#else
+	#ifdef ARM9
+		.cpu arm946e-s
+	#endif
+#endif
 
 	.text
 	.arm

**Comment by cotodevel** [comment]
Ok. I''l start with spinlock part then.

Also, i'll revert to heap size 64K and see if NIFI works. Because if it doesn't i'll stick with 128K size.

**Pull request closed without merging**
